import { createClient } from "@supabase/supabase-js";
export const supabase = createClient("https://jfvmafmnayscnqzsdpxm.supabase.co", "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impmdm1hZm1uYXlzY25xenNkcHhtIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2NjMwOTU4OCwiZXhwIjoyMDgxODg1NTg4fQ.UqI1zpOIY83LzcG_HIY4h9FggmWJGWsRqOa8Q6lqomQ");
